### PR TITLE
Allow to use a .env file to override globals

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Description?      | Allow to use a .env file to override globals
| Type?             |  improvement
| How to test?      | Have a .env file to add like FO_URL="http://localhost2/" and check that is the used URL (instead of localhost) to reach the BO page.
| Possible impacts? | Nothing here, just an extra dependency (basic one).

### CODE REVIEW

**Comment by PrestaEdit** [comment]
Ping @boubkerbribri

**Comment by PrestaEdit** [comment]
Ping @boubkerbribri | @SimonGrn

**Comment by SimonGrn** [comment]
> Ping @boubkerbribri | @SimonGrn

Hey, thanks for the ping, but I'm no longer a PrestaShop employee.

**Comment by PrestaEdit** [comment]
Sorry @SimonGrn ! I've forgotten this. Oops :)

**Comment by boubkerbribri** [comment]
thanks @PrestaEdit

**Pull request merged**
